<?php

/**
 * @file
 * Allow multiple entities to be used in an entity form display.
 */

/**
 * Implements hook_hook_info().
 */
function flexiform_hook_info() {
  $hooks['flexiform_form_entity_entity_create'] = [
    'group' => 'flexiform',
  ];
  return $hooks;
}

/**
 * Implements hook_entity_type_build().
 */
function flexiform_entity_type_build(array &$entity_types) {
  $entity_form_display_type = $entity_types['entity_form_display'];
  $entity_form_display_type->setClass('Drupal\flexiform\FlexiformEntityFormDisplay');
  $entity_form_display_type->setFormClass('edit', 'Drupal\flexiform\Form\FlexiformEntityFormDisplayEditForm');
}